services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
    ports:
      - 5173:5173
    develop:
      watch:
        - action: sync
          path: .
          target: /app
